import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const figtree = Figtree({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-Figtree'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className} antialiased`}
      >
        <div className="bg-hero-sm lg:bg-hero-lg">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
